#!/bin/sh
echo Installing Locast2Plex
echo Trying to remember how to install it
echo This is a project and maybe I should get some help
echo Writing Linux scripts is not my strength
echo At the very least, I am submitting enough PRs to get a free t-shirt